### ISSUE TITLE
Uncaught TYPO3 Exception: #1233180480

### ISSUE THREAD

**Issue by Kaliumiodid** [undkonsorten/typo3-cute-mailing-ttaddress#2]
I upgraded to Typo3v12 a few months ago and now I get an uncaught Typo3 Exception #1233180480 (The method "find" is not supported by the repository. | TYPO3\CMS\Extbase\Persistence\Generic\Exception\UnsupportedMethodException thrown in file [...]/vendor/typo3/cms-extbase/Classes/Persistence/Repository.php in line 268. Requested URL: [...]/typo3/ajax/cutemailing/wizardUserPreview?token=--AnonymizedToken--&recipientList=3).

The issue comes up, when I create a new newsletter, select the (test) receivers and on the Preview page I get a message saying "Newsletter is not yet ready to be sent! Please choose a receiver group.". In the Typo3 log I find the message above.
My environment is:

- Typo3 v12.4.12
- PHP 8.1.27
- tt_address 7.1.0 (due to cute-mailing-ttaddress)
- cute-mailing-ttaddress 2.2.1
- cute-mailing 4.0.1

I already cleared the caches via Maintenance menu.

**Comment by kanow** [comment]
It's not an issue in typo3-cute-mailing but in typo3-cute-mailing-ttaddress. I pushed a new version right now. That should fix the error. Please update your typo3-cute-mailing-ttaddress and check it.

**Comment by Kaliumiodid** [comment]
Thanks a lot for the help. With the new version, sending works again.

**Comment by harleqeen** [comment]
Hi @Kaliumiodid,
i have exactly the same situation: i need to update to typo3 version 12 but need to keep tt_address 7.1.0. How did you manage to get typo3 version 12 to work with tt_address 7.1.0? Any help would be appreciated!
Regards

**Comment by Kaliumiodid** [comment]
Hi @harleqeen,
since I made the update several months ago, I am not sure, if I had any further problems with tt_address. As mentioned, the issue above was solved by installing the updated cute-mailing-tt-address. What is your problem?

**Comment by harleqeen** [comment]
Hi @Kaliumiodid,
thanks for your answer! I made some tests, i found out that i get an error that the recipients list cannot be loaded, when i try to send the newsletter. But it looks like that happens only when i try to send a "test" newsletter. I will reproduce this and open a new issue.
Thank you very much again.
